### ISSUE TITLE
Using PyPads in Docker

### ISSUE THREAD

**Issue by Rohrmose** [padre-lab-eu/pypads#8]
When trying to use PyPads (built from Source) inside a Docker Container you get following Error:

> 

```
2020-09-18 12:45:04.696 | INFO     | pypads.injections.setup.misc_setup:_call:70 - Tracking execution to run with id 6370a226e32f4da8853c486cd9c85594
2020-09-18 12:45:05.522 | WARNING  | pypads.app.base:start_track:612 - Active run doesn't match given input name Default-PyPads. Recreating new run.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pypads/app/base.py", line 614, in start_track
    self.api.start_run(experiment_id=experiment_name, nested=True)
  File "/usr/local/lib/python3.7/site-packages/pypads/app/api.py", line 61, in wrapper
    return Cmd(fn=f)(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypads/app/api.py", line 34, in __call__
    return self.__real_call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypads/app/misc/mixins.py", line 255, in __real_call__
    return self._fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypads/app/api.py", line 149, in start_run
    out = mlflow.start_run(run_id=run_id, experiment_id=experiment_id, run_name=run_name, nested=nested)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 159, in start_run
    active_run_obj = MlflowClient().create_run(experiment_id=exp_id_for_run, tags=tags)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/client.py", line 137, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 95, in create_run
    tags=[RunTag(key, value) for (key, value) in iteritems(tags)],
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 457, in create_run
    experiment = self.get_experiment(experiment_id)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 338, in get_experiment
    experiment = self._get_experiment(experiment_id)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 309, in _get_experiment
    databricks_pb2.RESOURCE_DOES_NOT_EXIST,
mlflow.exceptions.MlflowException: Could not find experiment with ID Default-PyPads

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sklearn_example.py", line 2, in <module>
    tracker = PyPads(uri="mlruns", autostart=True)
  File "/usr/local/lib/python3.7/site-packages/pypads/app/base.py", line 195, in __init__
    self.start_track()
  File "/usr/local/lib/python3.7/site-packages/pypads/app/base.py", line 617, in start_track
    self.api.start_run(experiment_id=experiment_name)
  File "/usr/local/lib/python3.7/site-packages/pypads/app/api.py", line 61, in wrapper
    return Cmd(fn=f)(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypads/app/api.py", line 34, in __call__
    return self.__real_call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypads/app/misc/mixins.py", line 255, in __real_call__
    return self._fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypads/app/api.py", line 149, in start_run
    out = mlflow.start_run(run_id=run_id, experiment_id=experiment_id, run_name=run_name, nested=nested)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 159, in start_run
    active_run_obj = MlflowClient().create_run(experiment_id=exp_id_for_run, tags=tags)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/client.py", line 137, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 95, in create_run
    tags=[RunTag(key, value) for (key, value) in iteritems(tags)],
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 457, in create_run
    experiment = self.get_experiment(experiment_id)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 338, in get_experiment
    experiment = self._get_experiment(experiment_id)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/file_store.py", line 309, in _get_experiment
    databricks_pb2.RESOURCE_DOES_NOT_EXIST,
mlflow.exceptions.MlflowException: Could not find experiment with ID Default-PyPads
```

For reference, here is the Dockerfile:
```
FROM python:3.7
COPY pypads .
RUN pip install GitPython==3.1.8
RUN pip install ipython==7.18.1
RUN pip install Pygments==2.6.1
RUN pip install scikit-learn==0.21.3
RUN pip install psutil==5.7.0
RUN pip install poetry
RUN poetry build
RUN pip install dist/pypads-0.3.2.tar.gz
```

**Comment by Weissger** [comment]
It seems like the experiment wasn't initialized correctly in your docker environment. Can you post a snippet showing the initialization of the tracker? I'm going to try to reproduce the issue.

**Comment by Rohrmose** [comment]
> Can you post a snippet showing the initialization of the tracker?

```
from pypads.app.base import PyPads
tracker = PyPads(uri="mlruns", autostart=True)
```

I also used an MLflow Project to set the entrypoint for my Experiment, here's the correspodning MLproject File:
```
name: example-docker

docker_env:
  image:  example-mlproject

entry_points:
  main:
    command: "python sklearn_example.py"
```
